### ISSUE TITLE
Issue with displaying the content of an uploaded file after multiple selections

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#67] opened 2021-07-08 19:45 UTC
## 🐛 Describe the bug

When the user reserve a DOI and chose a file to upload, and then update the file and re-upload it by reclicking on choose file, the display of the content of the file is not updated.

## 📜 To Reproduce
1. Go to http://localhost:3000/create
2. Click on `Has the data been registered and made publicly available?` `NO`
3. choose a file and load it in the form (see compressed test dataset)
4. update locally the chosen file
5. choose a file again
The displayed content of the file is not updated.

## 🕵️ Expected behavior

The content displayed in the form should be updated as well as the content sent to the API back-end.

## 📚 Version of Software Used

origin/route-fixes, commit 4c59199

## 🩺 Test Data / Additional context

[DOI_Reserved_DEMO.csv.zip](https://github.com/NASA-PDS/pds-doi-ui/files/6786883/DOI_Reserved_DEMO.csv.zip)

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by eddiesarevalo** [comment] 2022-01-04 21:47
This is a duplicate of #87

**Closed** 2022-01-20 21:30 UTC
Labels: bug, B12.1, sprint-backlog, needs:more-info, d.dont-forget-me, s.high
